-- MySQL Script generated by MySQL Workbench
-- Sun Apr 22 16:47:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema study_intonation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema study_intonation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `study_intonation` DEFAULT CHARACTER SET utf8 ;
USE `study_intonation` ;

-- -----------------------------------------------------
-- Table `study_intonation`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `study_intonation`.`Courses` ;

CREATE TABLE IF NOT EXISTS `study_intonation`.`Courses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dirname` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(250) NULL,
  `logo` VARCHAR(45) NULL,
  `difficulty` INT NULL,
  `category` VARCHAR(45) NULL,
  `releaseDate` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `study_intonation`.`Lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `study_intonation`.`Lessons` ;

CREATE TABLE IF NOT EXISTS `study_intonation`.`Lessons` (
  `id` INT UNSIGNED NOT NULL,
  `courseID` INT UNSIGNED NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(250) NULL,
  `shortDescription` VARCHAR(45) NULL,
  `logo` VARCHAR(45) NULL,
  `duration` INT NULL,
  PRIMARY KEY (`id`, `courseID`),
  INDEX `courseID_idx` (`courseID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `study_intonation`.`Tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `study_intonation`.`Tasks` ;

CREATE TABLE IF NOT EXISTS `study_intonation`.`Tasks` (
  `id` INT UNSIGNED NOT NULL,
  `lessonID` INT UNSIGNED NOT NULL,
  `courseID` INT UNSIGNED NOT NULL,
  `instruction` VARCHAR(250) NULL,
  `text` VARCHAR(150) NULL,
  `pathToAudio` VARCHAR(45) NULL,
  `pitch` VARCHAR(45) NULL,
  `textMarkup` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `courseID`, `lessonID`),
  INDEX `lessonID_idx` (`lessonID` ASC),
  INDEX `courseID_idx` (`courseID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `study_intonation`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `study_intonation`.`Users` ;

CREATE TABLE IF NOT EXISTS `study_intonation`.`Users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `study_intonation`.`Statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `study_intonation`.`Statistics` ;

CREATE TABLE IF NOT EXISTS `study_intonation`.`Statistics` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `userID` INT UNSIGNED NOT NULL,
  `taskID` INT UNSIGNED NOT NULL,
  `lessonID` INT UNSIGNED NOT NULL,
  `courseID` INT UNSIGNED NOT NULL,
  `CR` DOUBLE NULL,
  `MSE` DOUBLE NULL,
  `MSE_K` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `userID_idx` (`userID` ASC),
  INDEX `taskID_idx` (`taskID` ASC),
  INDEX `lessonID_idx` (`lessonID` ASC),
  INDEX `courseID_idx` (`courseID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
