INSERT INTO users VALUES
(1, 'student', 'student@spbstu.ru');

INSERT INTO courses VALUES
(1, 'StudyIntonation', 'Study Intonation', 'This course is for everyday discourse skills mastering. Starting with quite short phrases you will browse through a variety of speaking patterns to feel and train the melody of English speech. Learn to produce intonation \"in tune\" when speaking.',
'logo.png', 2, 'Everyday discourse', '18.02.2017'),
(2, 'CrashCourse', 'Crash Course', 'Meet the principle tones of English. Learn to produce them when speaking. Starting with quite short common phrases you will browse through a variety of speaking patterns to feel and train the melody of English speech',
'logo.png', 1, 'Example', '18.02.2017');

INSERT INTO lessons (id, courseID, title, description, logo, duration) VALUES
(1, 1, 'Everyday discourse', 'Lets start from the very beginning. Listen to the pattern, observe the pitch curve and try to repeat the phrase in tune looking at the pitch as if you sing a song. This warm-up will help you to get along with Study Intonation. Good luck!',
'01EverydayDiscourse/logo.png', 25),
(2, 1, 'Invitations. Make-Accept-Decline', 'Remember: Listen to the pattern, observe the pitch curve and try to repeat the phrase in tune, looking at the pitch as if you sing a song. Keep to the melody and tempo of the speech',
'02Invitations/logo.png', 15),
(3, 1, 'Show Your Emotions', 'Remember: Listen to the pattern, observe the pitch curve and try to repeat the phrase in tune, looking at the pitch as if you sing a song. Keep to the melody and tempo of the speech',
'03Emotions/logo.png', 15),
(4, 1, 'Speaking in academic context', 'Remember: Listen to the pattern, observe the pitch curve and try to repeat the phrase in tune, looking at the pitch as if you sing a song. Keep to the melody and tempo of the speech',
'04AcademicContext/logo.png', 15),
(1, 2, 'Разогрев', 'Небольшая разминка перед началом курса', '01/logo.png', 10),
(2, 2, 'Тренировка интонации', 'Пора взяться за дело', '02/logo.png', 15),
(3, 2, 'Берем вес', 'Пришло время испытать триумф', '03/logo.png', 53);

INSERT INTO tasks VALUES
(1, 1, 1, 'We start speaking with greetings', 'Hello!', '01EverydayDiscourse/l1t1.mp3', '01EverydayDiscourse/l1t1.pitch', '01EverydayDiscourse/l1t1.text'),
(2, 1, 1, "Fine! Let's go further", 'How are things?', '01EverydayDiscourse/l1t2.mp3', '01EverydayDiscourse/l1t2.pitch', '01EverydayDiscourse/l1t2.text'),
(3, 1, 1, 'Fine! One more:', 'How are you?', '01EverydayDiscourse/l1t3.mp3', '01EverydayDiscourse/l1t3.pitch', '01EverydayDiscourse/l1t3.text'),
(4, 1, 1, "Fine! Let's reply:", 'Fine, thanks!', '01EverydayDiscourse/l1t4.mp3', '01EverydayDiscourse/l1t4.pitch', '01EverydayDiscourse/l1t4.text'),
(5, 1, 1, 'You are great! One more:', 'Very well! Thanks!!', '01EverydayDiscourse/l1t5.mp3', '01EverydayDiscourse/l1t5.pitch', '01EverydayDiscourse/l1t5.text'),
(6, 1, 1, 'Perfect! Try a longer phrase:', 'Good morning! Did you sleep well?', '01EverydayDiscourse/l1t6.mp3', '01EverydayDiscourse/l1t6.pitch', '01EverydayDiscourse/l1t6.text'),
(7, 1, 1, "Fine! Let's reply:", 'Yes! Very well, thanks! And you?', '01EverydayDiscourse/l1t7.mp3', '01EverydayDiscourse/l1t7.pitch', '01EverydayDiscourse/l1t7.text'),
(8, 1, 1, 'You are great! Now observe the slight difference in intonation:', 'Yeah! Not too bad, thanks!', '01EverydayDiscourse/l1t8.mp3', '01EverydayDiscourse/l1t8.pitch', '01EverydayDiscourse/l1t8.text'),
(9, 1, 1, 'Perfect! What if to try this:', 'I think I know you.', '01EverydayDiscourse/l1t9.mp3', '01EverydayDiscourse/l1t9.pitch', '01EverydayDiscourse/l1t9.text'),
(10, 1, 1, 'Great! Go further. Good luck!', "It's Julia, isn't it?", '01EverydayDiscourse/l1t10.mp3', '01EverydayDiscourse/l1t10.pitch', '01EverydayDiscourse/l1t10.text'),
(11, 1, 1, 'Perfect! Go on! Go on!', "It's Alan, isn't it?", '01EverydayDiscourse/l1t11.mp3', '01EverydayDiscourse/l1t11.pitch', '01EverydayDiscourse/l1t11.text'),
(12, 1, 1, "You are doing very well! Now, let's see how to introduce yourself. Try this pitch with different names: Mary Smith, Mohamed Salah, Andy Williams, Gennady Popov, Aya Kanazava, Wo Sung Tung and many more...", "I am Bryan Jacobs", '01EverydayDiscourse/l1t12.mp3', '01EverydayDiscourse/l1t12.pitch', '01EverydayDiscourse/l1t12.text'),
(13, 1, 1, "You are great! One more:", "I am Sophie Johns!", '01EverydayDiscourse/l1t13.mp3', '01EverydayDiscourse/l1t13.pitch', '01EverydayDiscourse/l1t13.text'),
(14, 1, 1, "Fine! Now, this pitch is warm and friendly. Try it with different names: Mary, Mohamed, Andy, Gennady, Charlie, Tung and all your favorite names", "Pleased to meet you, Bryan!", '01EverydayDiscourse/l1t14.mp3', '01EverydayDiscourse/l1t14.pitch', '01EverydayDiscourse/l1t14.text'),
(15, 1, 1, "Oh, it is a really job! Keep your progress:", "Pleased to meet you, too!", '01EverydayDiscourse/l1t15.mp3', '01EverydayDiscourse/l1t15.pitch', '01EverydayDiscourse/l1t15.text'),
(16, 1, 1, "Perfect! This pitch is confident:", "I've had a lot to do!", '01EverydayDiscourse/l1t16.mp3', '01EverydayDiscourse/l1t16.pitch', '01EverydayDiscourse/l1t16.text'),
(17, 1, 1, "Oh! This pitch is regretting:", "I had to cancel the meeting!", '01EverydayDiscourse/l1t17.mp3', '01EverydayDiscourse/l1t17.pitch', '01EverydayDiscourse/l1t17.text'),
(18, 1, 1, "And this one is full of gratitude:", "I'd really appreciate that!", '01EverydayDiscourse/l1t18.mp3', '01EverydayDiscourse/l1t18.pitch', '01EverydayDiscourse/l1t18.text'),
(19, 1, 1, "Perfect! Let's say it in tune:", "Are you going for lunch now?", '01EverydayDiscourse/l1t19.mp3', '01EverydayDiscourse/l1t19.pitch', '01EverydayDiscourse/l1t19.text'),
(20, 1, 1, "Look at this short, but very rich pitch:", "Oh, yes, I am!", '01EverydayDiscourse/l1t20.mp3', '01EverydayDiscourse/l1t20.pitch', '01EverydayDiscourse/l1t20.text'),
(21, 1, 1, "You are doing very well! Proceed:", "Do you mind if I join you for lunch?", '01EverydayDiscourse/l1t21.mp3', '01EverydayDiscourse/l1t21.pitch', '01EverydayDiscourse/l1t21.text'),
(22, 1, 1, "Fine! This one is tough, but not for you:", "Have you had a chance to look around the city yet?", '01EverydayDiscourse/l1t22.mp3', '01EverydayDiscourse/l1t22.pitch', '01EverydayDiscourse/l1t22.text'),
(23, 1, 1, "One more regretting pitch:", "Not yet, unfortunately.", '01EverydayDiscourse/l1t23.mp3', '01EverydayDiscourse/l1t23.pitch', '01EverydayDiscourse/l1t23.text'),
(24, 1, 1, "Now it's time to show your skills!", "I know we haven't met before but could I have a word with you, please?", '01EverydayDiscourse/l1t24.mp3', '01EverydayDiscourse/l1t24.pitch', '01EverydayDiscourse/l1t24.text'),
(25, 1, 1, "Wow! Profesor H. says:I am impressed. Absolutely! Just a couple of tasks, and we are done.", "I am glad! That's really kind of you, thank you!", '01EverydayDiscourse/l1t25.mp3', '01EverydayDiscourse/l1t25.pitch', '01EverydayDiscourse/l1t25.text'),
(26, 1, 1, "And the last one for now. Shy and diffifent pitch:", "I am sorry for I'm bothering you...", '01EverydayDiscourse/l1t26.mp3', '01EverydayDiscourse/l1t26.pitch', '01EverydayDiscourse/l1t26.text'),
(1, 2, 1, "Invitation for dinner", "Would you like to join me for dinner?", '02Invitations/l2t1.mp3', '02Invitations/l2t1.pitch', '02Invitations/l2t1.text'),
(2, 2, 1, "Proposal 1 (Infinitive Construction)", "Would you like to visit the museum?", '02Invitations/l2t2.mp3', '02Invitations/l2t2.pitch', '02Invitations/l2t2.text'),
(3, 2, 1, "Proposal 2 (Using the Gerund)", "Would you be intereseted in going to see an exhibition?", '02Invitations/l2t3.mp3', '02Invitations/l2t3.pitch', '02Invitations/l2t3.text'),
(4, 2, 1, "Proposal 3 (\"A why don't...\" proposal)", "Why don't you join us for a cup of coffee?", '02Invitations/l2t4.mp3', '02Invitations/l2t4.pitch', '02Invitations/l2t4.text'),
(5, 2, 1, "Proposal 4 (\"A how about...\" proposal)", "How about going to the theatre tonight?", '02Invitations/l2t5.mp3', '02Invitations/l2t5.pitch', '02Invitations/l2t5.text'),
(6, 2, 1, "Accepting the invitation 1", "Thank you very much!", '02Invitations/l2t6.mp3', '02Invitations/l2t6.pitch', '02Invitations/l2t6.text'),
(7, 2, 1, "Accepting the invitation 2", "That would be very nice!", '02Invitations/l2t7.mp3', '02Invitations/l2t7.pitch', '02Invitations/l2t7.text'),
(8, 2, 1, "Accepting the invitation 3", "Thank you for inviting me!", '02Invitations/l2t8.mp3', '02Invitations/l2t8.pitch', '02Invitations/l2t8.text'),
(9, 2, 1, "Accepting the invitation 4", "I look for it!", '02Invitations/l2t9.mp3', '02Invitations/l2t9.pitch', '02Invitations/l2t9.text'),
(10, 2, 1, "Accepting the invitation 5", "Thank you! That would be a pleasure!", '02Invitations/l2t10.mp3', '02Invitations/l2t10.pitch', '02Invitations/l2t10.text'),
(11, 2, 1, "Accepting the invitation 6", "That's very kind of you! I'd love to come!", '02Invitations/l2t11.mp3', '02Invitations/l2t11.pitch', '02Invitations/l2t11.text'),
(12, 2, 1, "Accepting the invitation 7", "Thanks! That sounds great!", '02Invitations/l2t12.mp3', '02Invitations/l2t12.pitch', '02Invitations/l2t12.text'),
(13, 2, 1, "Accepting the invitation 8", "That sounds like fun!", '02Invitations/l2t13.mp3', '02Invitations/l2t13.pitch', '02Invitations/l2t13.text'),
(14, 2, 1, "Declining the invitation 1", "That's very kind of you, but I don't think I can.", '02Invitations/l2t14.mp3', '02Invitations/l2t14.pitch', '02Invitations/l2t14.text'),
(15, 2, 1, "Declining the invitation 2", "Thanks! But I don't think I can make it then.", '02Invitations/l2t15.mp3', '02Invitations/l2t15.pitch', '02Invitations/l2t15.text'),
(1, 3, 1, "??", "I thought it was pretty awful.", '03Emotions/l3t1.mp3', '03Emotions/l3t1.pitch', '03Emotions/l3t1.text'),
(2, 3, 1, "??", "Oh, really?", '03Emotions/l3t2.mp3', '03Emotions/l3t2.pitch', '03Emotions/l3t2.text'),
(3, 3, 1, "??", "I thought it was all right.", '03Emotions/l3t3.mp3', '03Emotions/l3t3.pitch', '03Emotions/l3t3.text'),
(4, 3, 1, "??", "I thought there was quite a lot of stuff there that was irrelevant too.", '03Emotions/l3t4.mp3', '03Emotions/l3t4.pitch', '03Emotions/l3t4.text'),
(5, 3, 1, "??", "That was useful!", '03Emotions/l3t5.mp3', '03Emotions/l3t5.pitch', '03Emotions/l3t5.text'),
(6, 3, 1, "??", "So, I came out feeling as though I wasted my time, to be honest.", '03Emotions/l3t6.mp3', '03Emotions/l3t6.pitch', '03Emotions/l3t6.text'),
(7, 3, 1, "??", "I am really impressed!", '03Emotions/l3t7.mp3', '03Emotions/l3t7.pitch', '03Emotions/l3t7.text'),
(8, 3, 1, "??", "It was fantastic, very inspirational, I've really enjoyed it!", '03Emotions/l3t8.mp3', '03Emotions/l3t8.pitch', '03Emotions/l3t8.text'),
(9, 3, 1, "??", "Oh, my! Such a wonderful thing!", '03Emotions/l3t9.mp3', '03Emotions/l3t9.pitch', '03Emotions/l3t9.text'),
(10, 3, 1, "??", "It's so nice, isn't it?", '03Emotions/l3t10.mp3', '03Emotions/l3t10.pitch', '03Emotions/l3t10.text'),
(11, 3, 1, "??", "Looks fantastic!", '03Emotions/l3t11.mp3', '03Emotions/l3t11.pitch', '03Emotions/l3t11.text'),
(12, 3, 1, "??", "Terrific! I love it!", '03Emotions/l3t12.mp3', '03Emotions/l3t12.pitch', '03Emotions/l3t12.text'),
(13, 3, 1, "??", "What a wonderful picture!", '03Emotions/l3t13.mp3', '03Emotions/l3t13.pitch', '03Emotions/l3t13.text'),
(14, 3, 1, "??", "Good job! Congratulations!", '03Emotions/l3t14.mp3', '03Emotions/l3t14.pitch', '03Emotions/l3t14.text'),
(15, 3, 1, "??", "You are terrific!", '03Emotions/l3t15.mp3', '03Emotions/l3t15.pitch', '03Emotions/l3t15.text'),
(16, 3, 1, "??", "Do you really thinks so? Thanks!", '03Emotions/l3t16.mp3', '03Emotions/l3t16.pitch', '03Emotions/l3t16.text'),
(17, 3, 1, "??", "I'm glad you liked it.", '03Emotions/l3t17.mp3', '03Emotions/l3t17.pitch', '03Emotions/l3t17.text'),
(18, 3, 1, "??", "How nice of you to say so!", '03Emotions/l3t18.mp3', '03Emotions/l3t18.pitch', '03Emotions/l3t18.text'),
(19, 3, 1, "??", "In fact, the credit should also go to my colleagues.", '03Emotions/l3t19.mp3', '03Emotions/l3t19.pitch', '03Emotions/l3t19.text'),
(20, 3, 1, "??", "It was nothing special, really.", '03Emotions/l3t20.mp3', '03Emotions/l3t20.pitch', '03Emotions/l3t20.text'),
(1, 4, 1, "??", "How's the conference going for you?", '04AcademicContext/l4t1.mp3', '04AcademicContext/l4t1.pitch', '04AcademicContext/l4t1.text'),
(2, 4, 1, "??", "What's your area of expertise?", '04AcademicContext/l4t2.mp3', '04AcademicContext/l4t2.pitch', '04AcademicContext/l4t2.text'),
(3, 4, 1, "??", "And I've got an abstract as well which you could have, if that helps.", '04AcademicContext/l4t3.mp3', '04AcademicContext/l4t3.pitch', '04AcademicContext/l4t3.text'),
(4, 4, 1, "??", "I'll go for the first method.", '04AcademicContext/l4t4.mp3', '04AcademicContext/l4t4.pitch', '04AcademicContext/l4t4.text'),
(5, 4, 1, "??", "My topic today is...", '04AcademicContext/l4t5.mp3', '04AcademicContext/l4t5.pitch', '04AcademicContext/l4t5.text'),
(6, 4, 1, "??", "I think you were at my presentation yesterday, weren't you?", '04AcademicContext/l4t6.mp3', '04AcademicContext/l4t6.pitch', '04AcademicContext/l4t6.text'),
(7, 4, 1, "??", "You know, I'm a great admirer of your work and the presentation really impressed me!", '04AcademicContext/l4t7.mp3', '04AcademicContext/l4t7.pitch', '04AcademicContext/l4t7.text'),
(8, 4, 1, "??", "I wonder, if we could perhaps meet up later on to discuss...", '04AcademicContext/l4t8.mp3', '04AcademicContext/l4t8.pitch', '04AcademicContext/l4t8.text'),
(9, 4, 1, "??", "We were in the same workshop this morning.", '04AcademicContext/l4t9.mp3', '04AcademicContext/l4t9.pitch', '04AcademicContext/l4t9.text'),
(10, 4, 1, "??", "I think we were at the same session yesterday, but we didn't have a chance to speak.", '04AcademicContext/l4t10.mp3', '04AcademicContext/l4t10.pitch', '04AcademicContext/l4t10.text'),
(11, 4, 1, "??", "What's your interest in my field of work?", '04AcademicContext/l4t11.mp3', '04AcademicContext/l4t11.pitch', '04AcademicContext/l4t11.text'),
(12, 4, 1, "??", "I'll be delighted because it's great to meet someone else who's interested in the same sort of issues that I am.", '04AcademicContext/l4t12.mp3', '04AcademicContext/l4t12.pitch', '04AcademicContext/l4t12.text'),
(1, 1, 2, "Ой, да делай что хочешь!", "I'm going to talk about greatest ideas of computer science", '01/01.mp3', '01/01.pitch', '01/01.text'),
(2, 1, 2, "Теперь попробуй что-то другое...", "So computer science is not the same thing as ICT", '01/02.mp3', '01/02.pitch', '01/02.text'),
(3, 1, 2, "Повторяй интонацию за диктором и тогда сможешь через некоторое время научиться интонационному выделению в английском языке", "It is not really even about programming", '01/03.mp3', '01/03.pitch', '01/03.text'),
(1, 2, 2, "Делай все как я говорю", "It is really about ideas that make computing possible", '02/01.mp3', '02/01.pitch', '02/01.text'),
(2, 2, 2, "Не сомневайся, просто доверься мне", "It is not really even about programming", '02/02.mp3', '02/02.pitch', '02/02.text'),
(3, 2, 2, "Повторяй интонацию за диктором и тогда сможешь через некоторое время научиться интонационному выделению в английском языке", "So computer science is not the same thing as ICT", '02/03.mp3', '02/03.pitch', '02/03.text'),
(1, 3, 2, "Делай на автомате, покажи мастерство", "It is really about ideas that make computing possible", '03/01.mp3', '03/01.pitch', '03/01.text'),
(2, 3, 2, "Не сомневайся, просто доверься мне", "So computer science is not the same thing as ICT", '03/02.mp3', '03/02.pitch', '03/02.text'),
(3, 3, 2, "Повторяй интонацию за диктором и тогда сможешь через некоторое время научиться интонационному выделению в английском языке", "I'm going to talk about greatest ideas of computer science", '03/03.mp3', '03/03.pitch', '03/03.text'),
(4, 3, 2, "Повторяй интонацию за диктором и тогда сможешь через некоторое время научиться интонационному выделению в английском языке", "It is not really even about programming", '03/04.mp3', '03/04.pitch', '03/04.text');





