export const CONFIG_UPDATE = 'CONFIG_UPDATE';
export const UPDATE_MAILCAT_STATE = 'UPDATE_MAILCAT_STATE';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';

export const FOLDERS_REQUEST = 'FOLDERS_REQUEST';
export const FOLDERS_SUCCESS = 'FOLDERS_SUCCESS';
export const FOLDERS_FAILURE = 'FOLDERS_FAILURE';

export const MESSAGES_REQUEST = 'MESSAGES_REQUEST';
export const MESSAGES_SUCCESS = 'MESSAGES_SUCCESS';
export const MESSAGES_FAILURE = 'MESSAGES_FAILURE';